### ISSUE TITLE
jsdom window won't be created

### ISSUE THREAD

**Issue by oschrenk** [shinout/browser#1]
I have problems running the the login sample2. It seems that the jsdom window object won't be created.

```
    [...]
    $b.browse(function(err, out) {
      console.log ("creating jsdom window");
      var window = jsdom(out.result).createWindow();
      console.log ("created jsdom window");
      var $ = jquery.create(window);
      var postdata = {
        Email  : userdata.email,
        Passwd : userdata.pass
      };
      var url = $("#gaia_loginform").attr("action");
      // get hidden fields, and register them to post data
      $("input").each(function(k, el) {
        var $el = $(el);
        var name = $el.attr("name"), type = $el.attr("type"), val = $el.val();
        if (type == "hidden" || type == "submit") postdata[name] = val;
      });
      return [url, {
        data  : postdata, // set post data
        method: "POST"    // set HTTP method (default: GET)
      }];
    })
    .after("login"); // browse after browsing with label="login"
    [...]
```

I added some log statements and never get "created jsdom window" back.

Maybe jsdom changed the API? `npm install browser` installs jsdom 0.2.9 for me.

**Comment by shinout** [comment]
Thanks for reporting bugs, and sorry not reply for a long time.

I found this bug is due to junjo's error reporting.
Setting new dependency to the fixed version of junjo (v0.2.6), I updated browser.js (v0.2.4).
I tried jsdom v0.2.9 and it worked well.

try
$ npm update browser

Then please check if it works well in your environment.
I prepared the test script of sample2 (test/manual_login.js).
After setting userdata object in test/accounts/google.json, you can run the test.

**Comment by oschrenk** [comment]
Thanks for working on the issue. I still have problems though.

```
rm -r node_modules
npm install browser
cd node_modules/browser/test
```

I removed the the first line of `manual_login.js` - `var userdata = require('./accounts/google');` (as the file is missing in the repo) and just set `userdata.email` and `userdata.pass` directly.

`node manual_login.js` then gave me:

```
The "sys" module is now called "util". It should have a similar interface.
 redirect count 0 / 10 
 cookie  
 userAgent (node.js default) 
 referer (null) 
 -----REQUEST INFORMATION ----------- 
 access to  https://accounts.google.com/Login 
 options { debug: true,
  cookie: '',
  ua: '',
  host: 'accounts.google.com',
  port: 443,
  path: '/Login',
  protocol: 'https',
  body: '' } 
 header { 'User-Agent': 'node.js/v0.6.0 (darwin) http.clientRequest',
  Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'Accept-Language': 'ja,en-us;q=0.7,en;q=0.3',
  'Accept-Charset': 'Shift_JIS,utf-8;q=0.7,*;q=0.7',
  'Keep-Alive': 120,
  Connection: 'keep-alive' } 
 ------------------------------------ 

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Cannot read property 'result' of undefined
    at [object Function].<anonymous> (/Users/Oliver/Development/projects/personal/node-duebooks/node_modules/browser/test/manual_login.js:38:22)
    at Array.3 (/Users/Oliver/Development/projects/personal/node-duebooks/node_modules/browser/node_modules/junjo/lib/Junjo.js:307:80)
    at EventEmitter._tickCallback (node.js:192:40)
```

Maybe I'm calling it in a wrong way.

**Comment by shinout** [comment]
Thanks for your feedback.
I found the problem is that Junjo.js does not work in Node.js v0.6.0.

It is because Function#apply() does not allow arguments object to be passed to the second argument from v0.6.0.
I sometimes pass arguments object to Function#apply() in Junjo.js (or some other libraries, teribble...).
I'm going to fix these invalid use for v0.6.0.
(just inserting Array.prototype.slice.call(arguments))
In Japan it's almost 9:00 AM, so I'll fix this bug and report you again after work.

**Comment by shinout** [comment]
Sorry, I mistook about the reason of the error.
Forget about the previous comment.

The reason is that  from Node v0.6.0 http modules starts to use "protocol" option.

I've updated the version to v0.2.5, then it can work in Node >=v0.6.
Thanks for reporting.

**Comment by oschrenk** [comment]
Nice. Thanks a lot. That fixed the issue for me!
